% Copyright Jean-Marie Mirebeau, University Paris-Sud, CNRS, University Paris-Saclay, 2020

if verLessThan('matlab','8.1')
    cxxFlags = ['CXXFLAGS="-std=c++17" ' ...
        'CXXLIBS="\$CXXLIBS -lc++" ' ]; % This flag is required on some platforms, but must be commented on others...
    outputFlag = '-o ';
else
    cxxFlags = 'CXXFLAGS="-std=c++17" ';
    outputFlag = '-output ';
end

compileHFM = @(binary_Dir,name,flag) eval(['mex ' ...
    outputFlag 'MatlabHFM_' name ' ../MatlabHFM.cpp' ...
    ' COMPFLAGS="/std:c++17"' ... % needed on windows 
    ' -outdir ' binary_Dir ...
    ' ' cxxFlags  '-D' flag ...
    ' -I' '../../../Headers' ...
    ' -I' '../../../JMM_CPPLibs' ...
    ]);

compileModelsHFM = @(binary_Dir,modelNames) ...
    cellfun(@(name) compileHFM(binary_Dir,name,['ModelName=' name]), modelNames);

standardModelsHFM = {'Isotropic2','Isotropic3','Diagonal2','Diagonal3',...
    'Riemann2','Riemann3','ReedsShepp2','ReedsSheppForward2','Elastica2',...
    'Dubins2','ReedsShepp3','ReedsSheppForward3'};

% Experimental models involved in some of the examples
%experimentalModelsHFM = {'IsotropicDiff2','RiemannLifted2_Periodic','DubinsExt2'};
experimentalModelsHFM = {'Seismic2','SeismicTopographic2','Seismic3','SeismicTopographic3','AlignedBillard','Riemann4',...
'Riemann5','Elastica2_9','ElasticaExt2_5','ReedsSheppExt2','ReedsSheppForwardExt2','RiemannDiff2',...
'RiemannLifted2_Periodic','Rander2',...
'AsymmetricQuadratic2','AsymmetricQuadratic3','AsymmetricQuadratic3p1','Riemann3_Periodic','AsymRander2'};

fprintf(['\nPlease execute the function compileModelsHFM(binary_Dir,standardModelsHFM) to build \n'...
'the Hamilton Fast Marching executables in directory binary_Dir, \n' ...
'In case of need, replace standardModelsHFM with experimentalModelsHFM, or any list of desired models.\n']);

%For me : binary_Dir = '/Users/mirebeau/Dropbox/Programmes/MATLAB/MexBin';
% or : binary_Dir = 'C:\Users\jmmir\Documents\bin\MatlabHFM';
%For debug : compileHFM(binary_Dir,'Custom','Custom')
