package:
    name: hfm
    version: 0.2.6

source:
    git_url: https://github.com/Mirebeau/HamiltonFastMarching

build:
    number: 1000
    string: py{{ environ.get('PYTHON_VERSION', 'unk') }}

requirements:
    channels:
        - conda-forge
#        - agd-lbr # Does not seem to work, channel added in conda-build command
    host:
        - python {{PY_VER}}*
    build:
        - {{ compiler('cxx') }}
        - setuptools
        - pybind11
        - numpy
        - cmake
        - git
    run:
        - python {{PY_VER}}*
        - numpy
        - agd 

test:
    imports:
        HFMpy.HFM_Isotropic2

about:
    dev_url: https://github.com/Mirebeau/HamiltonFastMarching
    license: Licence GPU GPL v3
    license_family: GPL

extra:
    recipe-maintainers:
        - gouarin
        - hleclerc
        
